"""Notion Integration API Router for SC Task Lens.

Manages Notion API token, database schema fetching, test connection endpoints,
and flexible database field mapping configuration.
"""

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
import json
from typing import List, Dict, Any
from sc_task_lens.database import get_db
from sc_task_lens.models import NotionConfig, NotionFieldMapping
from sc_task_lens.schemas import NotionConfigUpdate, NotionConfigOut, NotionMappingBatchUpdate, NotionFieldMappingSchema
from sc_task_lens.services.notion_service import NotionService, extract_notion_id

router = APIRouter(prefix="/api/notion", tags=["Notion Integration"])

AVAILABLE_TASK_FIELDS = [
    {"field": "title", "label": "Task Title", "description": "Actionable task name generated by AI"},
    {"field": "summary", "label": "Summary", "description": "Brief task summary or full description text"},
    {"field": "priority", "label": "Priority Level", "description": "Mapped Notion priority field (e.g. High, Medium, Low)"},
    {"field": "start_date", "label": "Start Date", "description": "Date when work on task should start"},
    {"field": "deadline", "label": "Due Date", "description": "Extracted due date"},
    {"field": "source_url", "label": "Reference URL", "description": "Actual HTTP/HTTPS URL extracted from screenshot or manual ref"},
    {"field": "project", "label": "Project/Category", "description": "Mapped project, team, or label context"},
    {"field": "attachment", "label": "Screenshot Image", "description": "Uploaded screenshot file attached directly"}
]

@router.get("/config", response_model=NotionConfigOut)
def get_config(db: Session = Depends(get_db)):
    config = db.query(NotionConfig).first()
    if not config:
        config = NotionConfig(api_token="", database_id="", database_title="")
        db.add(config)
        db.commit()
        db.refresh(config)

    return NotionConfigOut(
        id=config.id,
        api_token_configured=bool(config.api_token),
        database_id=config.database_id,
        database_title=config.database_title,
        last_schema_json=config.last_schema_json
    )

@router.post("/config", response_model=NotionConfigOut)
def update_config(payload: NotionConfigUpdate, db: Session = Depends(get_db)):
    config = db.query(NotionConfig).first()
    if not config:
        config = NotionConfig()
        db.add(config)
    
    config.api_token = payload.api_token.strip()
    config.database_id = extract_notion_id(payload.database_id)

    if config.api_token and config.database_id:
        res = NotionService.fetch_database_schema(config.api_token, config.database_id)
        if res.get("success"):
            config.database_title = res.get("database_title", "Notion Database")
            config.last_schema_json = json.dumps(res.get("properties", []))
    
    db.commit()
    db.refresh(config)

    return NotionConfigOut(
        id=config.id,
        api_token_configured=bool(config.api_token),
        database_id=config.database_id,
        database_title=config.database_title,
        last_schema_json=config.last_schema_json
    )

@router.post("/fetch-schema")
def fetch_schema(db: Session = Depends(get_db)):
    config = db.query(NotionConfig).first()
    if not config or not config.api_token or not config.database_id:
        raise HTTPException(status_code=400, detail="Please save your Notion API token and Database ID first.")

    res = NotionService.fetch_database_schema(config.api_token, config.database_id)
    if not res.get("success"):
        raise HTTPException(status_code=400, detail=res.get("error"))

    config.database_title = res.get("database_title")
    config.last_schema_json = json.dumps(res.get("properties"))
    db.commit()

    return {
        "success": True,
        "database_title": config.database_title,
        "properties": res.get("properties")
    }

@router.get("/task-fields")
def get_available_task_fields():
    return AVAILABLE_TASK_FIELDS

@router.get("/mapping")
def get_mapping(db: Session = Depends(get_db)):
    mappings = db.query(NotionFieldMapping).all()
    mapping_dict = {m.task_field: m for m in mappings}
    
    result = []
    for tf in AVAILABLE_TASK_FIELDS:
        f_name = tf["field"]
        existing = mapping_dict.get(f_name)
        result.append({
            "task_field": f_name,
            "label": tf["label"],
            "description": tf["description"],
            "notion_property_name": existing.notion_property_name if existing else "",
            "notion_property_type": existing.notion_property_type if existing else "",
            "value_mappings_json": existing.value_mappings_json if existing else None
        })
    return result

@router.post("/mapping")
def save_mapping(payload: NotionMappingBatchUpdate, db: Session = Depends(get_db)):
    """Save custom mappings between task candidate details and Notion database properties."""
    for item in payload.mappings:
        mapping = db.query(NotionFieldMapping).filter(NotionFieldMapping.task_field == item.task_field).first()
        if not mapping:
            mapping = NotionFieldMapping(
                task_field=item.task_field,
                notion_property_name=item.notion_property_name,
                notion_property_type=item.notion_property_type,
                value_mappings_json=item.value_mappings_json
            )
            db.add(mapping)
        else:
            mapping.notion_property_name = item.notion_property_name
            mapping.notion_property_type = item.notion_property_type
            mapping.value_mappings_json = item.value_mappings_json
    
    db.commit()
    return {"message": "Custom Notion field mapping configuration saved successfully!"}
